name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      - name: Setup nodeJS
        uses: actions/setup-node@v4
        with:
          node-version: '22.19.0'
      
      - name: Install dependencies
        run: |
          cd client
          npm install

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_JOLLY_STONE_0CC039400 }}
          action: "upload"
          app_location: "client"
          output_location: "dist"
