name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
      
      - name: Set up Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '22.19.0'
          
      - name: Install and Build App
        run: |
          # Go to the app folder
          cd client
          # Install dependencies
          npm install
          # Run the build command
          npm run build
          # The output will be in client/dist (based on your output_location)

      - name: Deploy Pre-built Artifacts
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_JOLLY_STONE_0CC039400 }}
          action: "upload"
          app_location: "client"
          output_location: "dist"
          skip_app_build: true