name: Deploy Backend

on:
  push:
    branches: [ main ]
    paths: [ 'backend/**' ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - name: Login to ACR
      run: |
        az acr login --name lostandfound6e7c665094dd0f40acr
        
    - name: Build and push services
      run: |
        cd backend/auth-service
        docker build -t lostandfound6e7c665094dd0f40acr.azurecr.io/lostandfound-auth:latest .
        docker push lostandfound6e7c665094dd0f40acr.azurecr.io/lostandfound-auth:latest
        
        cd ../items-service
        docker build -t lostandfound6e7c665094dd0f40acr.azurecr.io/lostandfound-items:latest .
        docker push lostandfound6e7c665094dd0f40acr.azurecr.io/lostandfound-items:latest
        
        cd ../api-gateway
        docker build -t lostandfound6e7c665094dd0f40acr.azurecr.io/lostandfound-gateway:latest .
        docker push lostandfound6e7c665094dd0f40acr.azurecr.io/lostandfound-gateway:latest
        
    - name: Update container apps
      run: |
        az containerapp update --name lostandfound-auth --resource-group ${{ secrets.RESOURCE_GROUP }} --image lostandfound6e7c665094dd0f40acr.azurecr.io/lostandfound-auth:latest
        az containerapp update --name lostandfound-items --resource-group ${{ secrets.RESOURCE_GROUP }} --image lostandfound6e7c665094dd0f40acr.azurecr.io/lostandfound-items:latest
        az containerapp update --name lostandfound-gateway --resource-group ${{ secrets.RESOURCE_GROUP }} --image lostandfound6e7c665094dd0f40acr.azurecr.io/lostandfound-gateway:latest